create table "public"."operation" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "date" date not null,
    "patient_id" bigint
);


create table "public"."patient" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name_first" text,
    "name_last" text,
    "surgeon_id" uuid,
    "dob" date not null
);


alter table "public"."patient" enable row level security;

create table "public"."reading" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "date" date not null,
    "psi" real not null,
    "patient_id" bigint not null
);


CREATE UNIQUE INDEX operation_pkey ON public.operation USING btree (id);

CREATE UNIQUE INDEX patient_pkey ON public.patient USING btree (id);

CREATE UNIQUE INDEX reading_pkey ON public.reading USING btree (id);

alter table "public"."operation" add constraint "operation_pkey" PRIMARY KEY using index "operation_pkey";

alter table "public"."patient" add constraint "patient_pkey" PRIMARY KEY using index "patient_pkey";

alter table "public"."reading" add constraint "reading_pkey" PRIMARY KEY using index "reading_pkey";

alter table "public"."operation" add constraint "operation_patient_id_fkey" FOREIGN KEY (patient_id) REFERENCES patient(id) not valid;

alter table "public"."operation" validate constraint "operation_patient_id_fkey";

alter table "public"."patient" add constraint "patient_surgeon_id_fkey" FOREIGN KEY (surgeon_id) REFERENCES auth.users(id) not valid;

alter table "public"."patient" validate constraint "patient_surgeon_id_fkey";

alter table "public"."reading" add constraint "reading_patient_id_fkey" FOREIGN KEY (patient_id) REFERENCES patient(id) not valid;

alter table "public"."reading" validate constraint "reading_patient_id_fkey";

create policy "Enable all for authenticated users only"
on "public"."operation"
as permissive
for all
to authenticated
with check (true);


create policy "Surgeons Can Perform All Operations on their Own Patients"
on "public"."patient"
as permissive
for all
to authenticated
using ((surgeon_id = auth.uid()))
with check ((surgeon_id = auth.uid()));




