create table "public"."patient" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name_last" text,
    "name_first" text,
    "dob" date
);


alter table "public"."patient" enable row level security;

CREATE UNIQUE INDEX patient_pkey ON public.patient USING btree (id);

alter table "public"."patient" add constraint "patient_pkey" PRIMARY KEY using index "patient_pkey";


